spring:
  profiles:
    active: exntu-dev,log
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

# Security 설정
security:
  oauth2:
    # OAuth 서버 Client 정보
    client:
      client-id: registry
      client-secret: registry-secret
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
    auth-server-uri: http://localhost:8081/oauth/token
    keycloak:
      auth-server-uri: https://btvpaas-dev-keycloak.skbroadband.com/auth
      client-id: registry
      realm: nextpaas
      adminUser: keycloak
      adminPassword: ehdwkrxkzh1!

# LOG 설정
logging:
  config: classpath:logback.xml

# WAS 설정
server:
  port: 8081
  servlet:
    session:
      timeout: 120m

# Config
config:
  cache:
    url: exntu.kr
    port: 6379
    password:
  token:
    url: http://localhost:8080/oauth/token

---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Local Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: local

  # DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/registry?useUnicode=true&characterEncoding=utf-8
    username: registry
    password: registry1234$$
    hikari:
      max-lifetime: 600000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
#      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        hbm2ddl:
          import_files: /sql/init.sql

# Config
config:
  builder:
    url: http://192.168.201.146:4000
    username: builder
  minio:
    available: true
  time-zone: Asia/Seoul
  registry:
    url: localhost:5000
  file:
    upload_dir: /tmp/file
  oauth:
    jwt:
      issuer: taco-registry
      key: classpath:registry.jks
      password: taco-registry
      key-pair-alias: servercert
      key-pair-password: taco-registry
---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Exntu Dev Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: exntu-dev

  # DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exntu?useUnicode=true&characterEncoding=utf-8
    username: exntu
    password: exntu123!
    hikari:
      max-lifetime: 600000
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: none
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        hbm2ddl:
          import_files: /sql/init.sql

# Config
config:
  builder:
    url: http://192.168.201.146:4000
    username: builder
  minio:
    available: true
  time-zone: Asia/Seoul
  registry:
    url: 192.168.201.146:5000
  file:
    upload_dir: /tmp/file
  oauth:
    jwt:
      issuer: taco-registry
      key: classpath:registry.jks
      password: taco-registry
      key-pair-alias: servercert
      key-pair-password: taco-registry
---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Log Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: log
  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# LOG 설정
logging:
  config: classpath:logback-console.xml
---
