spring:
  profiles:
    active: prod,log
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

  # DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://taco-db:5432/${POSTGRES_DB:registry}?useUnicode=true&characterEncoding=utf-8
    username: ${POSTGRES_USER:registry}
    password: ${POSTGRES_PASSWORD:registry1234$$}

  # Redis
  redis:
    host: taco-redis
    port: 6379
    password:
    timeout: 60

# Ribbon
builder:
  username: builder
  redis:
    key: builderList
    health_uri: /v1/health
    connect-timeout: 3000
  ribbon:
    eureka:
      enabled: false
    NIWSServerListClassName: com.registry.config.RibbonServerList
    ServerListRefreshInterval: 15000

# Security 설정
security:
  oauth2:
    # OAuth 서버 Client 정보
    client:
      client-id: registry
      client-secret: registry-secret
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

# LOG 설정
logging:
  config: classpath:logback.xml

# WAS 설정
server:
  port: 8080
  servlet:
    session:
      timeout: 120m

# Config
config:
  file:
    upload_dir: /tmp/file
  oauth:
    jwt:
      issuer: ${REGISTRY_AUTH_ISSUER:taco-registry}
      key: classpath:registry.jks
      password: ${REGISTRY_AUTH_KEY_PASSWORD:registry.starkube.com}
      key-pair-alias: ${REGISTRY_AUTH_KEY_PAIR_ALIAS:servercert}
      key-pair-password: ${REGISTRY_AUTH_KEY_PAIR_PASSWORD:exntu}

---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Product Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        hbm2ddl:
          import_files: /sql/init.sql
---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Product Create Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: prod-create

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        hbm2ddl:
          import_files: /sql/init.sql
---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Log Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: log
  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# LOG 설정
logging:
  config: classpath:logback-console.xml
---
