spring:
  profiles:
    active: exntu-dev,log
  jmx:
    enabled: false
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

# Security 설정
security:
  oauth2:
    # OAuth 서버 Client 정보
    client:
      client-id: registry
      client-secret: registry-secret
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

# LOG 설정
logging:
  config: classpath:logback.xml

# WAS 설정
server:
  port: 8080
  servlet:
    session:
      timeout: 120m

# Config
config:
  cache:
    url: exntu.kr
    port: 6379
    password:
  token:
    url: http://localhost:8080/oauth/token

---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Local Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: local

  # DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/registry?useUnicode=true&characterEncoding=utf-8
    username: registry
    password: registry1234$$
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
#      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        hbm2ddl:
          import_files: /sql/init.sql

  # Redis
  redis:
    host: localhost
    port: 6379
    password:

# Ribbon
builder:
  username: builder
  redis:
    key: builderList
    health_uri: /v1/health
    connect-timeout: 3000
  ribbon:
    eureka:
      enabled: false
    NIWSServerListClassName: com.registry.config.RibbonServerList
    ServerListRefreshInterval: 15000

# Config
config:
  time-zone: Asia/Seoul
  registry:
    url: localhost:5000
  file:
    upload_dir: /tmp/file
  oauth:
    jwt:
      issuer: taco-registry
      key: classpath:registry.jks
      password: registry.starkube.com
      key-pair-alias: servercert
      key-pair-password: exntu
---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Exntu Dev Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: exntu-dev

  # DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.201.146:5432/registry?useUnicode=true&characterEncoding=utf-8
    username: registry
    password: registry1234$$
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
#      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        hbm2ddl:
          import_files: /sql/init.sql

  # Redis
  redis:
    host: 192.168.201.146
    port: 6379
    password:
    timeout: 60

# Ribbon
builder:
  username: builder
  redis:
    key: builderList
    health_uri: /v1/health
    connect-timeout: 3000
  ribbon:
    eureka:
      enabled: false
    NIWSServerListClassName: com.registry.config.RibbonServerList
    ServerListRefreshInterval: 15000

# Config
config:
  time-zone: Asia/Seoul
  registry:
    url: 192.168.201.146:5000
  file:
    upload_dir: /tmp/file
  oauth:
    jwt:
      issuer: taco-registry
      key: classpath:registry.jks
      password: registry.starkube.com
      key-pair-alias: servercert
      key-pair-password: exntu
---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Log Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: log
  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# LOG 설정
logging:
  config: classpath:logback-console.xml
---
