/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './main.module';
import * as i2 from './main.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/http';
import * as i6 from '../repository/repository.service';
import * as i7 from '../organization/organization.service';
import * as i8 from './main.service';
import * as i9 from '@angular/router';
import * as i10 from '../../common/component/selectbox/select-box.module';
import * as i11 from '../../common/component/pagination/pagination.module';
import * as i12 from '../../common/component/file-upload/file-upload.module';
import * as i13 from '../../common/component/autocomplete/autocomplete.module';
import * as i14 from '../../common/shared.module';
import * as i15 from '../gnb/organization-area/organization-area.module';
import * as i16 from '../gnb/profile-area/profile-area.module';
import * as i17 from './main.component';
export const MainModuleNgFactory:i0.NgModuleFactory<i1.MainModule> = i0.ɵcmf(i1.MainModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.MainComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,i5.BrowserXhr,i5.BrowserXhr,
              ([] as any[])),i0.ɵmpd(4608,i5.ResponseOptions,i5.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(5120,i5.XSRFStrategy,i5.ɵb,([] as any[])),i0.ɵmpd(4608,
              i5.XHRBackend,i5.XHRBackend,[i5.BrowserXhr,i5.ResponseOptions,i5.XSRFStrategy]),
          i0.ɵmpd(4608,i5.RequestOptions,i5.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i5.Http,i5.ɵc,[i5.XHRBackend,i5.RequestOptions]),i0.ɵmpd(4608,i6.RepositoryService,
              i6.RepositoryService,[i0.Injector]),i0.ɵmpd(4608,i7.OrganizationService,
              i7.OrganizationService,[i0.Injector]),i0.ɵmpd(4608,i8.MainService,i8.MainService,
              [i0.Injector]),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,([] as any[])),
          i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.FormsModule,i4.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i5.HttpModule,i5.HttpModule,([] as any[])),
          i0.ɵmpd(512,i9.RouterModule,i9.RouterModule,[[2,i9.ɵa],[2,i9.Router]]),i0.ɵmpd(512,
              i10.SelectBoxModule,i10.SelectBoxModule,([] as any[])),i0.ɵmpd(512,i11.PaginationModule,
              i11.PaginationModule,([] as any[])),i0.ɵmpd(512,i12.FileUploadModule,
              i12.FileUploadModule,([] as any[])),i0.ɵmpd(512,i13.AutocompleteModule,
              i13.AutocompleteModule,([] as any[])),i0.ɵmpd(512,i14.SharedModule,i14.SharedModule,
              ([] as any[])),i0.ɵmpd(512,i15.OrganizationAreaModule,i15.OrganizationAreaModule,
              ([] as any[])),i0.ɵmpd(512,i16.ProfileAreaModule,i16.ProfileAreaModule,
              ([] as any[])),i0.ɵmpd(512,i1.MainModule,i1.MainModule,([] as any[])),
          i0.ɵmpd(1024,i9.ROUTES,() => {
            return [[{path:'',component:i17.MainComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9tYWluL21haW4ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9tYWluL21haW4ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
