/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './repository.module';
import * as i2 from './repository.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/http';
import * as i6 from '../../repository/repository.service';
import * as i7 from '@angular/router';
import * as i8 from '../../../common/component/selectbox/select-box.module';
import * as i9 from '../../../common/component/pagination/pagination.module';
import * as i10 from '../../../common/component/file-upload/file-upload.module';
import * as i11 from '../../../common/component/autocomplete/autocomplete.module';
import * as i12 from '../../../common/shared.module';
import * as i13 from './repository.component';
export const RepositoryModuleNgFactory:i0.NgModuleFactory<i1.RepositoryModule> = i0.ɵcmf(i1.RepositoryModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.RepositoryComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,i5.BrowserXhr,i5.BrowserXhr,
              ([] as any[])),i0.ɵmpd(4608,i5.ResponseOptions,i5.BaseResponseOptions,
              ([] as any[])),i0.ɵmpd(5120,i5.XSRFStrategy,i5.ɵb,([] as any[])),i0.ɵmpd(4608,
              i5.XHRBackend,i5.XHRBackend,[i5.BrowserXhr,i5.ResponseOptions,i5.XSRFStrategy]),
          i0.ɵmpd(4608,i5.RequestOptions,i5.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i5.Http,i5.ɵc,[i5.XHRBackend,i5.RequestOptions]),i0.ɵmpd(4608,i6.RepositoryService,
              i6.RepositoryService,[i0.Injector]),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,
              i4.FormsModule,i4.FormsModule,([] as any[])),i0.ɵmpd(512,i5.HttpModule,
              i5.HttpModule,([] as any[])),i0.ɵmpd(512,i7.RouterModule,i7.RouterModule,
              [[2,i7.ɵa],[2,i7.Router]]),i0.ɵmpd(512,i8.SelectBoxModule,i8.SelectBoxModule,
              ([] as any[])),i0.ɵmpd(512,i9.PaginationModule,i9.PaginationModule,([] as any[])),
          i0.ɵmpd(512,i10.FileUploadModule,i10.FileUploadModule,([] as any[])),i0.ɵmpd(512,
              i11.AutocompleteModule,i11.AutocompleteModule,([] as any[])),i0.ɵmpd(512,
              i12.SharedModule,i12.SharedModule,([] as any[])),i0.ɵmpd(512,i1.RepositoryModule,
              i1.RepositoryModule,([] as any[])),i0.ɵmpd(1024,i7.ROUTES,() => {
            return [[{path:'',component:i13.RepositoryComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9vcmdhbml6YXRpb24vcmVwb3NpdG9yeS9yZXBvc2l0b3J5Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9leG50dS9JZGVhUHJvamVjdHMvcmVnaXN0cnkvcmVnaXN0cnktdWkvc3JjL2FwcC9sYXlvdXQvb3JnYW5pemF0aW9uL3JlcG9zaXRvcnkvcmVwb3NpdG9yeS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
