/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './test.component';
import * as i2 from '../common/component/selectbox/select-box.component.ngfactory';
import * as i3 from '../common/component/selectbox/select-box.component';
const styles_TestComponent:any[] = ([] as any[]);
export const RenderType_TestComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TestComponent,data:{}});
export function View_TestComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{selectBox:0}),i0.ɵqud(402653184,2,{selectBox2:0}),
      (_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(3,0,(null as any),
          (null as any),13,'div',[['class','taco-wrap']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
          ['\n  '])),(_l()(),i0.ɵted(-1,(null as any),['\n  '])),(_l()(),i0.ɵeld(6,
          0,(null as any),(null as any),9,'div',[['class','layout-content']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
          (null as any),['\n    '])),(_l()(),i0.ɵeld(8,0,(null as any),(null as any),
          1,'div',[['select-box','']],[[2,'component-selectbox',(null as any)],[2,
              'is-disabled',(null as any)]],[[(null as any),'onSelectedValues'],['document',
              'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i1.TestComponent = _v.component;
            if (('document:click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,9).documentClick($event)) !== false);
              ad = (pd_0 && ad);
            }
            if (('onSelectedValues' === en)) {
              const pd_1:any = ((<any>_co.selectedValues($event)) !== false);
              ad = (pd_1 && ad);
            }
            return ad;
          },i2.View_SelectBoxComponent_0,i2.RenderType_SelectBoxComponent)),i0.ɵdid(9,
          245760,[[1,4],['select1',4]],0,i3.SelectBoxComponent,[i0.ElementRef],(null as any),
          {onSelectedValues:'onSelectedValues'}),(_l()(),i0.ɵted(-1,(null as any),
          ['\n\n    '])),(_l()(),i0.ɵeld(11,0,(null as any),(null as any),1,'div',
          [['select-box','']],[[2,'component-selectbox',(null as any)],[2,'is-disabled',
              (null as any)]],[[(null as any),'onSelected'],['document','click']],
          (_v,en,$event) => {
            var ad:boolean = true;
            var _co:i1.TestComponent = _v.component;
            if (('document:click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,12).documentClick($event)) !== false);
              ad = (pd_0 && ad);
            }
            if (('onSelected' === en)) {
              const pd_1:any = ((<any>_co.selectedValue($event)) !== false);
              ad = (pd_1 && ad);
            }
            return ad;
          },i2.View_SelectBoxComponent_0,i2.RenderType_SelectBoxComponent)),i0.ɵdid(12,
          245760,[[2,4],['select2',4]],0,i3.SelectBoxComponent,[i0.ElementRef],(null as any),
          {onSelected:'onSelected'}),(_l()(),i0.ɵted(-1,(null as any),['\n\n\n    '])),
      (_l()(),i0.ɵeld(14,0,(null as any),(null as any),0,'input',[['id','minMaxDate'],
          ['readonly','readonly'],['type','text']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n  '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n\n'])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n']))],(_ck,_v) => {
    _ck(_v,9,0);
    _ck(_v,12,0);
  },(_ck,_v) => {
    const currVal_0:any = true;
    const currVal_1:any = i0.ɵnov(_v,9).isError;
    _ck(_v,8,0,currVal_0,currVal_1);
    const currVal_2:any = true;
    const currVal_3:any = i0.ɵnov(_v,12).isError;
    _ck(_v,11,0,currVal_2,currVal_3);
  });
}
export function View_TestComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-test',([] as any[]),
      (null as any),(null as any),(null as any),View_TestComponent_0,RenderType_TestComponent)),
      i0.ɵdid(1,245760,(null as any),0,i1.TestComponent,[i0.ElementRef,i0.Injector],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TestComponentNgFactory:i0.ComponentFactory<i1.TestComponent> = i0.ɵccf('app-test',
    i1.TestComponent,View_TestComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL3Rlc3QvdGVzdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXhudHUvSWRlYVByb2plY3RzL3JlZ2lzdHJ5L3JlZ2lzdHJ5LXVpL3NyYy9hcHAvdGVzdC90ZXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL3Rlc3QvdGVzdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL3Rlc3QvdGVzdC5jb21wb25lbnQudHMuVGVzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPGRpdiBjbGFzcz1cInRhY28td3JhcFwiPlxuICA8IS0tIENvbnRlbnQgLS0+XG4gIDxkaXYgY2xhc3M9XCJsYXlvdXQtY29udGVudFwiPlxuICAgIDxkaXYgc2VsZWN0LWJveCAjc2VsZWN0MVxuICAgICAgICAgKG9uU2VsZWN0ZWRWYWx1ZXMpPVwic2VsZWN0ZWRWYWx1ZXMoJGV2ZW50KVwiXG4gICAgPjwvZGl2PlxuXG4gICAgPGRpdiBzZWxlY3QtYm94ICNzZWxlY3QyXG4gICAgICAgICAob25TZWxlY3RlZCk9XCJzZWxlY3RlZFZhbHVlKCRldmVudClcIlxuICAgID48L2Rpdj5cblxuXG4gICAgPGlucHV0IHR5cGU9XCJ0ZXh0XCIgaWQ9XCJtaW5NYXhEYXRlXCIgdHlwZT1cInRleHRcIiByZWFkb25seT1cInJlYWRvbmx5XCI+XG4gIDwvZGl2PlxuXG48L2Rpdj5cbiIsIjxhcHAtdGVzdD48L2FwcC10ZXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O01DQUEsMENBQ0E7VUFBQTtVQUFBLDRDQUF1QjtVQUFBLFdBQ0wsNENBQ2hCO1VBQUE7VUFBQSwwREFBNEI7VUFBQSwyQkFDMUI7VUFBQTtjQUFBO2NBQUE7WUFBQTtZQUFBO1lBQUE7Y0FBQTtjQUFBO1lBQUE7WUFDSztjQUFBO2NBQUE7WUFBQTtZQURMO1VBQUEseUVBQUE7VUFBQTtVQUFBLHVDQUVPO1VBQUEsZUFFUDtVQUFBO2NBQUE7VUFBQTtZQUFBO1lBQUE7WUFBQTtjQUFBO2NBQUE7WUFBQTtZQUNLO2NBQUE7Y0FBQTtZQUFBO1lBREw7VUFBQSx5RUFBQTtVQUFBO1VBQUEsMkJBRU87TUFHUDtVQUFBO1VBQUEsOEJBQW1FO01BQy9ELDRDQUVGO1VBQUE7SUFaRjtJQUlBOztJQUpBO0lBQUE7SUFBQSxXQUFBLG1CQUFBO0lBSUE7SUFBQTtJQUFBLFlBQUEsbUJBQUE7Ozs7b0JDUko7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
