/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './admin.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
import * as i4 from '@angular/http';
import * as i5 from './admin-menu.guard';
import * as i6 from './user-list/super-user.service';
import * as i7 from '../../common/service/common.service';
import * as i8 from '@angular/router';
import * as i9 from '../../common/component/selectbox/select-box.module';
import * as i10 from '../../common/component/pagination/pagination.module';
import * as i11 from '../../common/component/file-upload/file-upload.module';
import * as i12 from '../../common/component/autocomplete/autocomplete.module';
import * as i13 from '../../common/shared.module';
export const AdminModuleNgFactory:i0.NgModuleFactory<i1.AdminModule> = i0.ɵcmf(i1.AdminModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ɵi,
          i3.ɵi,([] as any[])),i0.ɵmpd(4608,i4.BrowserXhr,i4.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i4.ResponseOptions,i4.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,
              i4.XSRFStrategy,i4.ɵb,([] as any[])),i0.ɵmpd(4608,i4.XHRBackend,i4.XHRBackend,
              [i4.BrowserXhr,i4.ResponseOptions,i4.XSRFStrategy]),i0.ɵmpd(4608,i4.RequestOptions,
              i4.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i4.Http,i4.ɵc,[i4.XHRBackend,
              i4.RequestOptions]),i0.ɵmpd(4608,i5.AdminMenuGuard,i5.AdminMenuGuard,
              [i6.SuperUserService,i7.CommonService,i0.Injector,i8.Router]),i0.ɵmpd(512,
              i2.CommonModule,i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.ɵba,i3.ɵba,
              ([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,([] as any[])),
          i0.ɵmpd(512,i4.HttpModule,i4.HttpModule,([] as any[])),i0.ɵmpd(512,i8.RouterModule,
              i8.RouterModule,[[2,i8.ɵa],[2,i8.Router]]),i0.ɵmpd(512,i9.SelectBoxModule,
              i9.SelectBoxModule,([] as any[])),i0.ɵmpd(512,i10.PaginationModule,i10.PaginationModule,
              ([] as any[])),i0.ɵmpd(512,i11.FileUploadModule,i11.FileUploadModule,
              ([] as any[])),i0.ɵmpd(512,i12.AutocompleteModule,i12.AutocompleteModule,
              ([] as any[])),i0.ɵmpd(512,i13.SharedModule,i13.SharedModule,([] as any[])),
          i0.ɵmpd(512,i1.AdminModule,i1.AdminModule,([] as any[])),i0.ɵmpd(1024,i8.ROUTES,
              () => {
                return [[{path:'',redirectTo:'user-list',pathMatch:'full'},{path:'user-list',
                    loadChildren:'app/layout/admin/user-list/user-list.module#UserListModule',
                    canActivate:[i5.AdminMenuGuard]}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9hZG1pbi9hZG1pbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXhudHUvSWRlYVByb2plY3RzL3JlZ2lzdHJ5L3JlZ2lzdHJ5LXVpL3NyYy9hcHAvbGF5b3V0L2FkbWluL2FkbWluLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
