/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './build-history.module';
import * as i2 from './build-history.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/http';
import * as i6 from '../../../common/service/docker.service';
import * as i7 from './build-history.service';
import * as i8 from '@angular/router';
import * as i9 from '../../../common/component/selectbox/select-box.module';
import * as i10 from '../../../common/component/pagination/pagination.module';
import * as i11 from '../../../common/component/file-upload/file-upload.module';
import * as i12 from '../../../common/component/autocomplete/autocomplete.module';
import * as i13 from '../../../common/shared.module';
import * as i14 from '../popup/build-popup.module';
import * as i15 from '../popup/copy-as-popup.module';
import * as i16 from '../repository-header.module';
import * as i17 from '../popup/build-detail-popup.module';
import * as i18 from './build-history.component';
export const BuildHistoryModuleNgFactory:i0.NgModuleFactory<i1.BuildHistoryModule> = i0.ɵcmf(i1.BuildHistoryModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.BuildHistoryComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,i5.BrowserXhr,
          i5.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i5.ResponseOptions,i5.BaseResponseOptions,
          ([] as any[])),i0.ɵmpd(5120,i5.XSRFStrategy,i5.ɵb,([] as any[])),i0.ɵmpd(4608,
          i5.XHRBackend,i5.XHRBackend,[i5.BrowserXhr,i5.ResponseOptions,i5.XSRFStrategy]),
          i0.ɵmpd(4608,i5.RequestOptions,i5.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i5.Http,i5.ɵc,[i5.XHRBackend,i5.RequestOptions]),i0.ɵmpd(4608,i6.DockerService,
              i6.DockerService,[i0.Injector]),i0.ɵmpd(4608,i7.BuildHistoryService,
              i7.BuildHistoryService,[i0.Injector]),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,
              i4.FormsModule,i4.FormsModule,([] as any[])),i0.ɵmpd(512,i5.HttpModule,
              i5.HttpModule,([] as any[])),i0.ɵmpd(512,i8.RouterModule,i8.RouterModule,
              [[2,i8.ɵa],[2,i8.Router]]),i0.ɵmpd(512,i9.SelectBoxModule,i9.SelectBoxModule,
              ([] as any[])),i0.ɵmpd(512,i10.PaginationModule,i10.PaginationModule,
              ([] as any[])),i0.ɵmpd(512,i11.FileUploadModule,i11.FileUploadModule,
              ([] as any[])),i0.ɵmpd(512,i12.AutocompleteModule,i12.AutocompleteModule,
              ([] as any[])),i0.ɵmpd(512,i13.SharedModule,i13.SharedModule,([] as any[])),
          i0.ɵmpd(512,i14.BuildPopupModule,i14.BuildPopupModule,([] as any[])),i0.ɵmpd(512,
              i15.CopyAsPopupModule,i15.CopyAsPopupModule,([] as any[])),i0.ɵmpd(512,
              i16.RepositoryHeaderModule,i16.RepositoryHeaderModule,([] as any[])),
          i0.ɵmpd(512,i17.BuildDetailPopupModule,i17.BuildDetailPopupModule,([] as any[])),
          i0.ɵmpd(512,i1.BuildHistoryModule,i1.BuildHistoryModule,([] as any[])),i0.ɵmpd(1024,
              i8.ROUTES,() => {
                return [[{path:'',component:i18.BuildHistoryComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9yZXBvc2l0b3J5L2J1aWxkLWhpc3RvcnkvYnVpbGQtaGlzdG9yeS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXhudHUvSWRlYVByb2plY3RzL3JlZ2lzdHJ5L3JlZ2lzdHJ5LXVpL3NyYy9hcHAvbGF5b3V0L3JlcG9zaXRvcnkvYnVpbGQtaGlzdG9yeS9idWlsZC1oaXN0b3J5Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
