/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './organization.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
import * as i4 from '@angular/http';
import * as i5 from './organization-menu.guard';
import * as i6 from './organization.service';
import * as i7 from '../../common/service/common.service';
import * as i8 from '@angular/router';
import * as i9 from '../../common/component/selectbox/select-box.module';
import * as i10 from '../../common/component/pagination/pagination.module';
import * as i11 from '../../common/component/file-upload/file-upload.module';
import * as i12 from '../../common/component/autocomplete/autocomplete.module';
import * as i13 from '../../common/shared.module';
export const OrganizationModuleNgFactory:i0.NgModuleFactory<i1.OrganizationModule> = i0.ɵcmf(i1.OrganizationModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ɵi,
          i3.ɵi,([] as any[])),i0.ɵmpd(4608,i4.BrowserXhr,i4.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i4.ResponseOptions,i4.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,
              i4.XSRFStrategy,i4.ɵb,([] as any[])),i0.ɵmpd(4608,i4.XHRBackend,i4.XHRBackend,
              [i4.BrowserXhr,i4.ResponseOptions,i4.XSRFStrategy]),i0.ɵmpd(4608,i4.RequestOptions,
              i4.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i4.Http,i4.ɵc,[i4.XHRBackend,
              i4.RequestOptions]),i0.ɵmpd(4608,i5.OrganizationMenuGuard,i5.OrganizationMenuGuard,
              [i6.OrganizationService,i7.CommonService,i0.Injector,i8.Router]),i0.ɵmpd(512,
              i2.CommonModule,i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.ɵba,i3.ɵba,
              ([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,([] as any[])),
          i0.ɵmpd(512,i4.HttpModule,i4.HttpModule,([] as any[])),i0.ɵmpd(512,i8.RouterModule,
              i8.RouterModule,[[2,i8.ɵa],[2,i8.Router]]),i0.ɵmpd(512,i9.SelectBoxModule,
              i9.SelectBoxModule,([] as any[])),i0.ɵmpd(512,i10.PaginationModule,i10.PaginationModule,
              ([] as any[])),i0.ɵmpd(512,i11.FileUploadModule,i11.FileUploadModule,
              ([] as any[])),i0.ɵmpd(512,i12.AutocompleteModule,i12.AutocompleteModule,
              ([] as any[])),i0.ɵmpd(512,i13.SharedModule,i13.SharedModule,([] as any[])),
          i0.ɵmpd(512,i1.OrganizationModule,i1.OrganizationModule,([] as any[])),i0.ɵmpd(1024,
              i8.ROUTES,() => {
                return [[{path:'',redirectTo:'image',pathMatch:'full'},{path:'image',
                    loadChildren:'app/layout/organization/repository/repository.module#RepositoryModule',
                    canActivate:[i5.OrganizationMenuGuard]},{path:'team',loadChildren:'app/layout/organization/role/role.module#RoleModule',
                    canActivate:[i5.OrganizationMenuGuard]},{path:'usage-log',loadChildren:'app/layout/organization/usage-log/usage-log.module#UsageLogModule',
                    canActivate:[i5.OrganizationMenuGuard]},{path:'setting',loadChildren:'app/layout/organization/setting/setting.module#SettingModule',
                    canActivate:[i5.OrganizationMenuGuard]}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9vcmdhbml6YXRpb24vb3JnYW5pemF0aW9uLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9leG50dS9JZGVhUHJvamVjdHMvcmVnaXN0cnkvcmVnaXN0cnktdWkvc3JjL2FwcC9sYXlvdXQvb3JnYW5pemF0aW9uL29yZ2FuaXphdGlvbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
