/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './loader.component';
const styles_LoaderComponent:any[] = ([] as any[]);
export const RenderType_LoaderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LoaderComponent,data:{}});
function View_LoaderComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),20,'div',[['class',
      'taco-loading']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n  '])),(_l()(),i0.ɵeld(2,0,(null as any),
          (null as any),17,'div',[['class','section-loading']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    '])),(_l()(),i0.ɵeld(4,0,(null as any),(null as any),14,'div',[['class',
          'loading-area']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n      '])),(_l()(),
          i0.ɵeld(6,0,(null as any),(null as any),11,'div',[['class','box-loading']],
              (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(8,0,(null as any),
          (null as any),8,'div',[['class','lds-roller']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵeld(9,0,(null as any),
          (null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵeld(10,0,(null as any),(null as any),
          0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵeld(11,0,(null as any),(null as any),0,'div',
          ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵeld(12,0,(null as any),(null as any),0,'div',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵeld(13,
          0,(null as any),(null as any),0,'div',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵeld(14,0,(null as any),
          (null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵeld(15,0,(null as any),(null as any),
          0,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵeld(16,0,(null as any),(null as any),0,'div',
          ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n      '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    '])),(_l()(),i0.ɵted(-1,(null as any),['\n  '])),(_l()(),i0.ɵted(-1,
          (null as any),['\n']))],(null as any),(null as any));
}
export function View_LoaderComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_LoaderComponent_1)),i0.ɵdid(2,
      16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),
      i0.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    var _co:i2.LoaderComponent = _v.component;
    const currVal_0:any = _co.show;
    _ck(_v,2,0,currVal_0);
  },(null as any));
}
export function View_LoaderComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'div',[['loader',
      '']],(null as any),(null as any),(null as any),View_LoaderComponent_0,RenderType_LoaderComponent)),
      i0.ɵdid(1,245760,(null as any),0,i2.LoaderComponent,[i0.ElementRef,i0.Injector],
          (null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const LoaderComponentNgFactory:i0.ComponentFactory<i2.LoaderComponent> = i0.ɵccf('[loader]',
    i2.LoaderComponent,View_LoaderComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2NvbW1vbi9jb21wb25lbnQvbG9hZGVyL2xvYWRlci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXhudHUvSWRlYVByb2plY3RzL3JlZ2lzdHJ5L3JlZ2lzdHJ5LXVpL3NyYy9hcHAvY29tbW9uL2NvbXBvbmVudC9sb2FkZXIvbG9hZGVyLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2NvbW1vbi9jb21wb25lbnQvbG9hZGVyL2xvYWRlci5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2NvbW1vbi9jb21wb25lbnQvbG9hZGVyL2xvYWRlci5jb21wb25lbnQudHMuTG9hZGVyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPCEtLSBMb2FkaW5nIC0tPlxuPGRpdiBjbGFzcz1cInRhY28tbG9hZGluZ1wiICpuZ0lmPVwic2hvd1wiPlxuICA8ZGl2IGNsYXNzPVwic2VjdGlvbi1sb2FkaW5nXCI+XG4gICAgPGRpdiBjbGFzcz1cImxvYWRpbmctYXJlYVwiPlxuICAgICAgPGRpdiBjbGFzcz1cImJveC1sb2FkaW5nXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJsZHMtcm9sbGVyXCI+PGRpdj48L2Rpdj48ZGl2PjwvZGl2PjxkaXY+PC9kaXY+PGRpdj48L2Rpdj48ZGl2PjwvZGl2PjxkaXY+PC9kaXY+PGRpdj48L2Rpdj48ZGl2PjwvZGl2PjwvZGl2PlxuICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG48IS0tIC8vTG9hZGluZyAtLT5cbiIsIjxkaXYgbG9hZGVyPjwvZGl2PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNDQTtNQUFBO01BQXVDLDRDQUNyQztVQUFBO1VBQUEsNENBQTZCO1VBQUEsYUFDM0I7VUFBQTtVQUFBLGdCQUEwQixnREFDeEI7aUJBQUE7Y0FBQTtNQUF5QixrREFDdkI7VUFBQTtVQUFBLDRDQUF3QjtVQUFBO1VBQUEsOEJBQVc7VUFBQTtVQUFBLGdCQUFXO1VBQUE7TUFBVztVQUFBLDBEQUFXO1VBQUE7VUFBQSw0Q0FBVztVQUFBO1VBQUEsOEJBQVc7VUFBQTtVQUFBLGdCQUFXO1VBQUE7TUFBaUIsZ0RBQ2xIO1VBQUEsYUFDRiw0Q0FDRjtVQUFBOzs7b0JBUlEsMENBQ2hCO01BQUEsNEVBQUE7TUFBQTtVQUFBLHdCQVFNLDBDQUNZO2FBQUE7O0lBVFE7SUFBMUIsV0FBMEIsU0FBMUI7Ozs7b0JDREE7TUFBQTthQUFBO1VBQUE7SUFBQTs7OzsifQ==
