/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './500.component';
const styles_Error500Component:any[] = ([] as any[]);
export const RenderType_Error500Component:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_Error500Component,data:{}});
export function View_Error500Component_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(1,0,
      (null as any),(null as any),13,'div',[['class','page-error']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n\n  '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),10,
      'div',[['class','error-area']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(5,
      0,(null as any),(null as any),1,'strong',[['class','txt-error']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['500 : Unexpected Error'])),(_l()(),i0.ɵted(-1,(null as any),
      ['\n    '])),(_l()(),i0.ɵeld(8,0,(null as any),(null as any),1,'p',[['class',
      'txt-desc']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['Something isn\'t quite right.'])),(_l()(),
          i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(11,0,(null as any),
          (null as any),1,'button',[['class','btn-action type-small'],['type','button']],
          (null as any),[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:i1.Error500Component = _v.component;
            if (('click' === en)) {
              const pd_0:any = ((<any>_co.mainPageClick()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['Main Page'])),
      (_l()(),i0.ɵted(-1,(null as any),['\n  '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n\n'])),(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵted(-1,
          (null as any),['\n']))],(null as any),(null as any));
}
export function View_Error500Component_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'error-500',
      ([] as any[]),(null as any),(null as any),(null as any),View_Error500Component_0,
      RenderType_Error500Component)),i0.ɵdid(1,245760,(null as any),0,i1.Error500Component,
      [i0.ElementRef,i0.Injector],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const Error500ComponentNgFactory:i0.ComponentFactory<i1.Error500Component> = i0.ɵccf('error-500',
    i1.Error500Component,View_Error500Component_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9lcnJvci81MDAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9lcnJvci81MDAuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvZXhudHUvSWRlYVByb2plY3RzL3JlZ2lzdHJ5L3JlZ2lzdHJ5LXVpL3NyYy9hcHAvbGF5b3V0L2Vycm9yLzUwMC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9lcnJvci81MDAuY29tcG9uZW50LnRzLkVycm9yNTAwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPCEtLSBQYWdlIDogRXJyb3IgLS0+XG48ZGl2IGNsYXNzPVwicGFnZS1lcnJvclwiPlxuXG4gIDxkaXYgY2xhc3M9XCJlcnJvci1hcmVhXCI+XG4gICAgPHN0cm9uZyBjbGFzcz1cInR4dC1lcnJvclwiPjUwMCA6IFVuZXhwZWN0ZWQgRXJyb3I8L3N0cm9uZz5cbiAgICA8cCBjbGFzcz1cInR4dC1kZXNjXCI+U29tZXRoaW5nIGlzbid0IHF1aXRlIHJpZ2h0LjwvcD5cbiAgICA8YnV0dG9uIHR5cGU9XCJidXR0b25cIiBjbGFzcz1cImJ0bi1hY3Rpb24gdHlwZS1zbWFsbFwiIChjbGljayk9XCJtYWluUGFnZUNsaWNrKClcIj5NYWluIFBhZ2U8L2J1dHRvbj5cbiAgPC9kaXY+XG5cbjwvZGl2PlxuPCEtLSAvL1BhZ2UgOiBFcnJvciAtLT5cbiIsIjxlcnJvci01MDA+PC9lcnJvci01MDA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQXFCLDBDQUNyQjtNQUFBO01BQUEsMERBQXdCO01BQUEsMkJBRXRCO01BQUE7TUFBQSxnQkFBd0IsOENBQ3RCO01BQUE7TUFBQSwwREFBMEI7TUFBQSwyQ0FBK0I7TUFBQSxhQUN6RDtNQUFBO01BQW9CLHFFQUFnQztpQkFBQSwrQkFDcEQ7VUFBQTtVQUFBO1lBQUE7WUFBQTtZQUFvRDtjQUFBO2NBQUE7WUFBQTtZQUFwRDtVQUFBLGdDQUE4RTtNQUFrQiw0Q0FDNUY7VUFBQSxXQUVGLDBDQUNpQjtVQUFBOzs7b0JDVnZCO01BQUE7a0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
