/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './error.module';
import * as i2 from './404.component.ngfactory';
import * as i3 from './500.component.ngfactory';
import * as i4 from './403.component.ngfactory';
import * as i5 from '@angular/router';
import * as i6 from './404.component';
import * as i7 from './500.component';
import * as i8 from './403.component';
export const ErrorModuleNgFactory:i0.NgModuleFactory<i1.ErrorModule> = i0.ɵcmf(i1.ErrorModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.Error404ComponentNgFactory,i3.Error500ComponentNgFactory,i4.Error403ComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,i5.RouterModule,
          i5.RouterModule,[[2,i5.ɵa],[2,i5.Router]]),i0.ɵmpd(512,i1.ErrorModule,i1.ErrorModule,
          ([] as any[])),i0.ɵmpd(1024,i5.ROUTES,() => {
        return [[{path:'',redirectTo:'404',pathMatch:'full'},{path:'404',component:i6.Error404Component},
            {path:'500',component:i7.Error500Component},{path:'403',component:i8.Error403Component}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2xheW91dC9lcnJvci9lcnJvci5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXhudHUvSWRlYVByb2plY3RzL3JlZ2lzdHJ5L3JlZ2lzdHJ5LXVpL3NyYy9hcHAvbGF5b3V0L2Vycm9yL2Vycm9yLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
