/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from './common/component/confirm-popup/confirm-popup.component.ngfactory';
import * as i3 from './common/component/confirm-popup/confirm-popup.component';
import * as i4 from './common/component/confirm-popup/confirm-popup.service';
import * as i5 from './common/component/loader/loader.component.ngfactory';
import * as i6 from './common/component/loader/loader.component';
import * as i7 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(1,16777216,
      (null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),i0.ɵdid(2,212992,(null as any),0,
      i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,i0.ComponentFactoryResolver,
          [8,(null as any)],i0.ChangeDetectorRef],(null as any),(null as any)),(_l()(),
      i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵted(-1,(null as any),['\n'])),
      (_l()(),i0.ɵeld(5,0,(null as any),(null as any),1,'div',[['confirm-popup','']],
          [[2,'layout-popup',(null as any)]],(null as any),(null as any),i2.View_ConfirmPopupComponent_0,
          i2.RenderType_ConfirmPopupComponent)),i0.ɵdid(6,245760,(null as any),0,i3.ConfirmPopupComponent,
          [i0.ElementRef,i0.Renderer,i4.ConfirmPopupService],(null as any),(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(8,0,(null as any),
          (null as any),1,'div',[['loader','']],(null as any),(null as any),(null as any),
          i5.View_LoaderComponent_0,i5.RenderType_LoaderComponent)),i0.ɵdid(9,245760,
          (null as any),0,i6.LoaderComponent,[i0.ElementRef,i0.Injector],(null as any),
          (null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n\n']))],(_ck,_v) => {
    _ck(_v,2,0);
    _ck(_v,6,0);
    _ck(_v,9,0);
  },(_ck,_v) => {
    const currVal_0:any = true;
    _ck(_v,5,0,currVal_0);
  });
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(1,49152,(null as any),0,i7.AppComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i7.AppComponent> = i0.ɵccf('app-root',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZXhudHUvSWRlYVByb2plY3RzL3JlZ2lzdHJ5L3JlZ2lzdHJ5LXVpL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2V4bnR1L0lkZWFQcm9qZWN0cy9yZWdpc3RyeS9yZWdpc3RyeS11aS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPCEtLSBXcmFwIC0tPlxuPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuPCEtLSAvLyBXcmFwIC0tPlxuPGRpdiBjb25maXJtLXBvcHVwPjwvZGl2PlxuPGRpdiBsb2FkZXI+PC9kaXY+XG5cbiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FhLDBDQUNiO01BQUE7TUFBQSxtREFBQTtzQkFBQTtVQUFBLHFFQUErQjthQUFBLDJCQUNmO01BQ2hCO1VBQUE7NkNBQUEsVUFBQTtVQUFBO01BQXlCLDBDQUN6QjtVQUFBO2lFQUFBLFVBQUE7VUFBQTtVQUFBLGVBQWtCO0lBSGxCO0lBRUE7SUFDQTs7SUFEQTtJQUFBLFdBQUEsU0FBQTs7OztvQkNIQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
